defaults: &defaults
  d_port: 587
  d_address: 'sendaikyodo.sakura.ne.jp'
  d_domain: 'senkyo.co.jp'
  d_user_name: 'shuhei@senkyo.co.jp'
  d_password: 'AokiYamada1'
  d_authentication: 'plain'
  d_enable_starttls_auto: true
development:
  <<: *defaults
  neat_setting: 800


test:
  <<: *defaults

production:
  <<: *defaults
